<script setup lang="ts">
import {computed,ref} from 'vue';import {useRestaurant} from '../store';import {money,balance,type Line} from '../domain';import OrderCard from '../components/OrderCard.vue';
const s=useRestaurant(),selected=ref<number|null>(null),zone=ref('Todas las zonas'),filter=ref('Todas'),search=ref(''),draft=ref<Line[]>([]);
const table=computed(()=>s.state.tables.find(t=>t.id===selected.value));
const session=computed(()=>selected.value?s.sessionFor(selected.value):undefined);
const orders=computed(()=>s.state.orders.filter(o=>o.sessionId===session.value?.id));
const tables=computed(()=>s.state.tables.filter(t=>(zone.value==='Todas las zonas'||t.zone===zone.value)&&(filter.value==='Todas'||(filter.value==='Libres'?!s.sessionFor(t.id):!!s.sessionFor(t.id)))));
const occupied=computed(()=>s.state.sessions.filter(x=>!x.closed).length);
const dishes=computed(()=>s.state.dishes.filter(d=>d.available&&d.name.toLowerCase().includes(search.value.toLowerCase())));
const canSee=computed(()=>s.role!=='Waiter'||session.value?.waiter===s.waiter);
function select(id:number){if(draft.value.length&&id!==selected.value&&!confirm('Cambiar de mesa descartará el pedido sin enviar. ¿Continuar?'))return;selected.value=id;draft.value=[];}
function add(id:number){const d=s.state.dishes.find(d=>d.id===id)!;draft.value.push({dishId:id,name:d.name,price:d.price,quantity:1,instructions:'',allergy:false});}
function send(){s.act(()=>{s.addOrder(session.value!.id,draft.value);draft.value=[];});}
</script>
<template><div class="page-heading"><div><p class="eyebrow">VISTA DEL SALÓN</p><h1>Mesas y pedidos</h1><p class="muted">Cada mesa, cada detalle. Todo en su lugar.</p></div><label v-if="s.canServe" class="waiter-select">Mesero responsable<select v-model="s.waiter"><option>Mesero 1</option><option>Mesero 2</option></select></label></div>
<div class="stats"><div><span class="stat-icon green">▦</span><div><small>Mesas disponibles</small><strong>{{s.state.tables.length-occupied}} <em>/ {{s.state.tables.length}}</em></strong></div></div><div><span class="stat-icon amber">◷</span><div><small>Mesas ocupadas</small><strong>{{occupied}}</strong></div></div><div><span class="stat-icon blue">♨</span><div><small>Pedidos en cocina</small><strong>{{s.state.orders.filter(o=>['Pending','Preparing'].includes(o.status)).length}}</strong></div></div><div><span class="stat-icon purple">✓</span><div><small>Listos para entregar</small><strong>{{s.state.orders.filter(o=>o.status==='Ready').length}}</strong></div></div></div>
<div class="table-layout"><section class="panel floor-panel"><div class="panel-heading"><h2>Mapa de mesas</h2><select v-model="zone" aria-label="Zona"><option>Todas las zonas</option><option>Salón principal</option><option>Terraza</option></select></div><div class="tabs"><button v-for="name in ['Todas','Libres','Ocupadas']" :class="{active:filter===name}" @click="filter=name">{{name}}</button><div class="legend"><i></i> Libre <i class="busy"></i> Ocupada</div></div><div class="floor"><div class="floor-label">SALÓN PRINCIPAL <span>⌁</span></div><div class="tables-grid"><button v-for="t in tables" :key="t.id" class="table-button" :class="{occupied:!!s.sessionFor(t.id),selected:selected===t.id,round:t.capacity===6}" @click="select(t.id)"><span class="chair top"></span><span class="chair bottom"></span><strong>{{t.code}}</strong><small>{{t.capacity}} personas</small><span class="table-status">{{s.sessionFor(t.id)?'Ocupada':'Libre'}}</span><span v-if="t.zone==='Terraza'" class="table-zone">Terraza</span></button></div><p v-if="!tables.length" class="empty">No hay mesas con este filtro.</p><div class="entrance">↑ ENTRADA PRINCIPAL</div></div><div class="floor-caption">Seleccioná una mesa para abrir su cuenta o gestionar pedidos.</div></section>
<aside class="panel detail-panel"><template v-if="!table"><div class="empty-detail"><span>▦</span><h2>Todo empieza en una mesa</h2><p>Seleccioná una mesa del mapa para ver su cuenta y tomar el pedido.</p><small>Sincronización en tiempo real activa.</small></div></template><template v-else><div class="panel-heading"><div><p class="eyebrow">{{table.zone}}</p><h2>Mesa {{table.code}}</h2></div><span class="pill" :class="session?'Pending':'Delivered'">{{session?'Ocupada':'Libre'}}</span></div><div class="detail-content"><template v-if="!session"><div class="empty"><h3>Lista para recibir</h3><p>{{table.capacity}} lugares disponibles</p><button v-if="s.canServe" class="primary wide" @click="s.act(()=>s.open(table!.id))">Abrir cuenta</button><p v-else>Mesero o administrador puede abrir la cuenta.</p></div></template><template v-else-if="canSee&&s.role!=='Kitchen'"><div class="account-summary"><small>{{session.waiter}}</small><strong>{{money(balance(s.state,session.id))}}</strong><span>Saldo pendiente</span></div><OrderCard v-for="o in orders" :key="o.id" :order="o"/><p v-if="!orders.length" class="empty">La cuenta todavía no tiene pedidos.</p>
<template v-if="s.canServe&&!session.payments.length"><h3>Nuevo pedido</h3><input v-model="search" placeholder="Buscar un platillo…" aria-label="Buscar platillo"/><div class="dish-picker"><button v-for="d in dishes" @click="add(d.id)"><span>{{d.icon}} {{d.name}}</span><b>{{money(d.price)}} ＋</b></button></div><div v-for="(line,i) in draft" :key="i" class="draft-line"><div class="inline"><strong>{{line.name}}</strong><button class="text-button" @click="draft.splice(i,1)" aria-label="Quitar platillo">✕</button></div><label>Cantidad<input type="number" min="1" max="99" v-model.number="line.quantity"/></label><label>Instrucciones<textarea v-model="line.instructions" maxlength="500" placeholder="Sin cebolla, término de cocción…"></textarea></label><label class="checkbox"><input type="checkbox" v-model="line.allergy"/> Alerta de alergia</label></div><button v-if="draft.length" class="primary wide" @click="send">Enviar {{draft.length}} líneas a cocina →</button></template><p v-else-if="session.payments.length" class="muted">Cuenta con pagos: no admite pedidos nuevos.</p></template><p v-else class="empty">Consultá esta cuenta con el mesero responsable o caja.</p></div></template></aside></div></template>